import { useRelationships } from '../../../content/relationships/useRelationships';
import { RelatedContent } from '../../engineering-stories/components/RelatedContent';
import { StorySection, BulletList, TechnicalProfile } from '../../engineering-stories/components/StorySections';
import { useServiceMetadata } from '../useServiceMetadata';
import type { Service } from '../types';

export function ServicePage({ service }: { service: Service }) {
  useServiceMetadata(service);
  const relationships = useRelationships(service.relationships);
  return <main className="min-h-screen bg-white"><a href="#service-content" className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-[110] focus:rounded-md focus:bg-white focus:px-4 focus:py-2 focus:shadow">Skip to service content</a><header className="bg-gradient-to-br from-slate-50 via-white to-blue-50 py-20 lg:py-28"><div className="container mx-auto max-w-4xl px-4 sm:px-6 lg:px-8"><p className="text-sm font-semibold uppercase tracking-wider text-blue-700">{service.hero.eyebrow}</p><h1 className="mt-3 text-4xl font-bold text-slate-900 sm:text-5xl">{service.title}</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-slate-600 sm:text-xl">{service.hero.summary}</p></div></header><article id="service-content" className="container mx-auto max-w-4xl space-y-16 px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><StorySection id="overview" title="Overview"><p>{service.description}</p></StorySection><StorySection id="capabilities" title="Capabilities"><BulletList items={service.capabilities} /></StorySection><StorySection id="deliverables" title="Typical Deliverables"><BulletList items={service.deliverables} /></StorySection><StorySection id="technologies" title="Technology Stack"><TechnicalProfile technologies={{ Technologies: service.technologies }} /></StorySection>{service.commonUseCases.length > 0 && <StorySection id="use-cases" title="Common Use Cases"><BulletList items={service.commonUseCases} /></StorySection>}{service.faqs.length > 0 && <StorySection id="faqs" title="Frequently Asked Questions"><div className="space-y-4">{service.faqs.map((faq) => <details key={faq.question} className="rounded-xl border border-slate-200 p-5"><summary className="cursor-pointer font-semibold text-slate-900">{faq.question}</summary><p className="mt-3">{faq.answer}</p></details>)}</div></StorySection>}<div className="space-y-12 border-t border-slate-200 pt-14"><RelatedContent relationships={relationships} /></div><section className="rounded-2xl bg-slate-900 p-8 text-white sm:p-10"><h2 className="text-2xl font-bold">{service.cta.heading}</h2><p className="mt-3 text-slate-300">{service.cta.description}</p><a href="/#contact" className="mt-6 inline-flex rounded-lg bg-white px-5 py-3 font-semibold text-slate-900 focus-ring">{service.cta.label}</a></section></article></main>;
}
